In [3]:
import pandas as pd

In [7]:
FileToLoad = "Loan_Stats.csv"
Data = pd.read_csv(FileToLoad)

In [9]:
Data.head()

,addr_state,loan_status,loan_amnt,int_rate,annual_inc,delinq_2yrs,open_acc,revol_bal,total_acc,collections_12_mths_ex_med,...,num_actv_bc_tl,num_bc_tl,num_sats,num_tl_30dpd,num_tl_90g_dpd_24m,pct_tl_nvr_dlq,pub_rec_bankruptcies,tax_liens,total_bal_ex_mort,dti
0,WA,Charged Off,14000,12.74%,49960,0,8,3453,21,0,...,1,12,8,0,0,100,1,0,10773,9.30
1,GA,Fully Paid,9900,5.32%,53000,1,10,6585,22,0,...,2,5,10,0,0,90,0,0,43218,19.47
2,IN,Fully Paid,3600,7.49%,120000,0,18,5658,33,0,...,1,3,18,0,0,100,1,0,36506,18.90
3,FL,Fully Paid,10000,12.74%,40000,0,7,9227,15,0,...,2,3,7,0,0,100,0,0,9227,8.85
4,OH,Charged Off,8400,11.39%,50000,0,14,12831,30,0,...,4,11,14,0,0,100,0,0,51591,15.63

In [11]:
#LC_X_remake = LC[['int_rate', 'loan_amnt', 'annual_inc', 'dti', 'delinq_2yrs', 'total_acc', 'open_acc',
       #   'pct_tl_nvr_dlq', 'pub_rec_bankruptcies', 'total_bal_ex_mort']].copy()
Shrunk_Data = Data[['int_rate', 'loan_amnt', 'annual_inc', 'dti', 'delinq_2yrs', 'total_acc', 'open_acc','pct_tl_nvr_dlq', 'pub_rec_bankruptcies', 'total_bal_ex_mort']].copy()

In [13]:
Shrunk_Data.describe

<bound method NDFrame.describe of        int_rate  loan_amnt  annual_inc    dti  delinq_2yrs  total_acc  \
0        12.74%      14000       49960   9.30            0         21
1         5.32%       9900       53000  19.47            1         22
2         7.49%       3600      120000  18.90            0         33
3        12.74%      10000       40000   8.85            0         15
4        11.39%       8400       50000  15.63            0         30
5        11.39%       9000       60000  19.58            0         25
6         6.99%      12000       56000  17.90            0         28
7         7.49%      10000       50000  26.43            0         19
8        10.49%       4000       50000  33.61            1         33
9         6.99%       4800      160000  12.66            0         18
10        7.24%       6000      125000   9.25            0         27
11       16.99%       2000       62000  16.43            0         20
12        7.49%      17000      120000   8.41            0         34
13       25.49%      35000      114000  14.04            0         31
14       15.99%      14000       43000  21.80            1          8
15       11.49%      10000      145000  13.31            2         30
16        5.32%      18000      205000  22.72            0         27
17       15.99%      14000       82000  31.07            0         31
18       12.74%      20000      135000  12.55            1         30
19       14.99%       5000       68000  22.50            0         18
20       11.39%       7100       32160  22.44            0         15
21       10.49%       9000      172000  21.71            0         30
22       10.49%      14400      130000  30.77            0         42
23        7.24%      10150       50000  29.60            0         21
24       12.74%      16000      130000   8.28            0         48
25        7.99%      12000      100000  28.82            0         65
26       15.99%      25000       95000  22.47            1         30
27        5.32%       1500       67000   5.95            1         16
28       11.44%       6000       25000  24.20            0         16
29        8.24%      15500       79000  24.32            0         44
...         ...        ...         ...    ...          ...        ...
262957   12.73%      20400       75000  25.06            0         23
262958   11.06%      22000       52000  15.69            0         10
262959    7.84%      15000       80000   2.76            0         12
262960   19.92%       1600       75000   5.78            0         22
262961   10.47%       5000       42000  15.46            0         28
262962    8.46%      15000       90000  34.17            0         27
262963   17.97%      12000      110000  11.74            0         41
262964   24.37%       8000       40000  43.50            0         17
262965   17.97%      15000      110000  12.87            0         11
262966   11.06%      14000       40000  16.35            0         15
262967   19.92%      15000       65000  28.14            1         29
262968   12.73%      13000      163000  19.27            0         23
262969   11.55%      20000       90000   4.81            0          4
262970   23.40%       6500       55000   6.35            1         10
262971    6.11%      27000       80000  16.14            0         21
262972   11.55%       8700       90000  10.68            2         33
262973    6.11%      17150      165000  10.81            0         44
262974   11.06%      15000        7000  97.94            0          5
262975   18.94%      15000       85000  29.37            1         25
262976    7.21%      11000       24000  65.70            0         19
262977   27.27%      10500       45100  31.85            0         15
262978    6.11%      10000       70000  11.81            0         31
262979   17.97%      28000      100000  13.90            0         10
262980    7.84%      19000       95000   0.71            0         18
262981   11.55%       9000       32000  13.35            1         11
262982   16.91%       7500      110000  13.20            0         17
262983   13.56%      35000      100000  14.80            0         26
262984    6.67%      35000       85000  22.15            0         52
262985   16.14%       5000       46400  16.85            0         18
262986   15.02%      23000       75000  20.95            1         28

        open_acc  pct_tl_nvr_dlq  pub_rec_bankruptcies  total_bal_ex_mort
0              8             100                     1              10773
1             10              90                     0              43218
2             18             100                     1              36506
3              7             100                     0               9227
4             14             100                     0              51591
5             13             100                     0              32412
6             13             100                     0              21540
7             13             100                     0              35187
8             10              87                     0             136208
9             13              94                     0              37985
10            16              59                     0              60622
11            10             100                     2              39824
12             9              94                     1              48682
13            17              87                     0              81780
14             3              87                     0              26572
15            13              66                     0              68390
16            23             100                     0             135895
17            18             100                     0             104008
18            21              89                     0              55911
19             6              94                     0              36168
20             9             100                     0              20805
21            15              96                     0              94190
22            22             100                     0              69480
23             9             100                     0              45347
24            16              97                     1              44263
25            14             100                     0             154720
26            18              90                     0              38809
27             5              93                     0              10658
28            11             100                     0              10041
29            32             100                     0              48213
...          ...             ...                   ...                ...
262957        15             100                     1              64937
262958         6             100                     0              19009
262959         8              75                     0               6859
262960        16             100                     0              20244
262961        10              92                     0              27533
262962        18             100                     0              94004
262963         9              75                     0              31337
262964         5             100                     0              77527
262965         9             100                     0              57036
262966         5             100                     0              21890
262967        18              93                     0              55323
262968        17             100                     0              73681
262969         3             100                     0              14359
262970         5              90                     0               7475
262971        15              95                     0              40263
262972        14              90                     0              27734
262973        17              97                     0             103290
262974         3             100                     0              14460
262975        16              91                     1              87951
262976         6              78                     0             119724
262977        12             100                     0              30903
262978         9              83                     0              16651
262979         3              80                     0              44989
262980        16             100                     0               4720
262981         7              81                     1              14685
262982         9              88                     1              43442
262983        11             100                     1              48697
262984        19              90                     0             171452
262985        10              72                     0              19979
262986        12              96                     0              40614

[262987 rows x 10 columns]>

In [17]:
Sampled_Data = Shrunk_Data.sample(frac=.1, replace=True)
Sampled_Data.describe

<bound method NDFrame.describe of        int_rate  loan_amnt  annual_inc    dti  delinq_2yrs  total_acc  \
69254    16.02%      12000       46531  23.88            0         28
98183    19.99%       2500       50000   4.61            0         20
167484    5.32%      15000       90000  15.04            0         22
40254     7.24%      16700       76000  18.82            0         23
148348   16.02%      35000      120000   9.43            0         17
107485   11.99%       3600       45000  25.44            0         35
189683    9.92%      24000      100000   7.23            0         16
240450   14.47%       2000      100000   6.64            0         22
71696    19.03%       2500       95000  15.17            2         31
192401    7.34%      15000       32000  39.61            0         32
218574   10.56%       6000       52000  21.23            0         20
162445   24.85%      25000      115000  21.74            3         29
140423   10.91%      10975       73000  24.92            0         24
10753    22.74%      24000       69600  13.91            0         34
95100     8.24%      20000       70000  15.48            0          6
1215     13.49%      13675       36000  17.40            0         15
49373    19.99%       5375       12500  41.98            1          9
226399   10.07%      15000      100000  17.65            1         34
145717    7.21%       7200       65000  16.27            1          7
12281     8.24%       9600       52000  12.42            1         13
81459     8.24%      35000      115000   8.05            0         22
137117    7.97%      19200      109000  14.07            1         30
238586    9.43%      18000       60000  15.72            0         39
184397   29.69%      32000      100000  32.49            0         71
180534   21.45%      17500      145000  19.08            0         19
11999     8.24%      12000       70000  16.37            0         30
213648    6.08%      10000       32500   6.06            0         21
211389   18.06%      28000       90000  44.71            0         54
169861   11.99%      24000       85000  17.27            0         31
192788    7.34%      11200       98000  31.85            0         22
...         ...        ...         ...    ...          ...        ...
141455   10.42%      12000       70000  24.88            0         20
88570    26.24%      16000       48568  34.91            0         35
245968   11.55%      10000       98000  11.45            1         32
118779    7.07%       8000       90212  23.33            0         32
67444     9.93%       5000       47776  20.67            0         54
172678    7.07%       9000       70000  11.74            0         24
201451   10.91%       8600       48000   9.39            0         33
81835    12.74%      10000       27040  30.89            1         10
116677    7.35%      13200       82000  11.02            0         23
241502   15.02%      15000       45000  22.85            0         43
73296    15.05%       3000      120000  19.05            2         46
67061     5.32%       5200       68000   4.08            0         26
122118   13.59%      20000       75000   4.19            0          4
256790    8.81%      18000       66435  17.08            0         40
255642   13.56%       6000       68000  13.24            1         15
167234   15.05%       3000       15000  10.32            0         11
227445    9.92%      12000       65000  16.55            0         24
239926   11.06%       5000       31000  22.57            0         14
228688    5.31%      13000      159996   9.86            0         14
225150   10.07%      12000       55556  27.28            0         25
34083    30.84%      28000       86846  20.09            0         13
76335    12.62%      16000       70000  34.96            0         27
119804   15.05%      12000       67000  12.65            0          9
80473     8.24%      24000      110000  13.82            0          8
205509   10.42%       2000       48000  22.48            0         26
116423   10.42%      24000       90000  23.55            0         60
193732   17.47%      35000      100000  15.82            2         29
256507   11.80%       3000       90000   4.55            1         13
236674    9.43%       2000       74400  10.65            0         15
13511     8.24%      10000      100000  13.67            0         25

        open_acc  pct_tl_nvr_dlq  pub_rec_bankruptcies  total_bal_ex_mort
69254         22             100                     1              21015
98183         17              95                     0              23030
167484        11             100                     0              56907
40254         11             100                     0              21333
148348         6             100                     0              22435
107485        12             100                     1              42191
189683         5              62                     0              12863
240450        11             100                     0              28364
71696         15              76                     0              62646
192401        17             100                     0              13983
218574        12             100                     0              29042
162445        19              88                     0              47212
140423        17              91                     0              53337
10753          9              94                     0              50306
95100          4             100                     0              14411
1215          11             100                     0              10605
49373          7              87                     0              11678
226399        18              97                     0              41212
145717         6             100                     0              30742
12281          7              92                     0              30124
81459          8             100                     0              41219
137117        13             100                     0              52385
238586        17              97                     0              32410
184397        21              96                     1             425319
180534        14             100                     1              75655
11999         10             100                     0              69024
213648        11             100                     0               5730
211389        34             100                     0             144641
169861        13             100                     0              70580
192788        13             100                     0             115580
...          ...             ...                   ...                ...
141455         7             100                     0              65956
88570         11             100                     0              67786
245968         8              93                     0              81927
118779        18             100                     0              60415
67444         25             100                     1              42676
172678         9              87                     0              17656
201451         8             100                     1               9665
81835          6              90                     0              10272
116677         9             100                     0              36893
241502        13             100                     1              63383
73296         17              95                     0             131656
67061         15             100                     0               3357
122118         2             100                     0              10644
256790        20             100                     0              38296
255642         6              93                     0              18807
167234        10             100                     0               2488
227445         8              86                     0              27843
239926        12             100                     0              22962
228688         6             100                     0              51255
225150        12              81                     0              42510
34083          9              84                     0              53387
76335          9             100                     0              56786
119804         7             100                     0              42261
80473          8             100                     0              28598
205509        14              69                     0              24899
116423        24             100                     0             112106
193732         8              78                     0              44021
256507         8              84                     0              12809
236674        10             100                     0              21216
13511         15             100                     0              51920

[26299 rows x 10 columns]>

In [ ]:
Sampled_Data.to_csv("")